/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Animal extends javax.swing.JFrame {

    /**
     * Creates new form fert
     */
    public Animal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Salary", "SLEEP HOURS", "COLOR", "Emp ID", "ST ID"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jTable2.setRowHeight(30);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField3.setMinimumSize(new java.awt.Dimension(75, 35));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Salary");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Emp ID");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\add.png")); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\animal_pp.png")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel7.setText("ANIMAL");

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\homeicon.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\delete.png")); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\refresh.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\update.png")); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\24\\search.png")); // NOI18N
        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Color");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Sleep Hours");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setText("st ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextField8))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextField9))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField7))
                            .addComponent(jTextField9)
                            .addComponent(jTextField8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean myflag=true;
        if(jTextField1.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter ID field", "Error", JOptionPane.ERROR_MESSAGE);  }
        else if(jTextField2.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter Name field", "Error", JOptionPane.ERROR_MESSAGE);  }
        else if(jTextField3.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter Quantity field", "Error", JOptionPane.ERROR_MESSAGE);  }
        else if(jTextField4.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter Salary field", "Error", JOptionPane.ERROR_MESSAGE);  }
        
        else if(jTextField7.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter Sleep Hours field", "Error", JOptionPane.ERROR_MESSAGE);  }
        else if(jTextField8.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter Color field", "Error", JOptionPane.ERROR_MESSAGE);  }
        else if(jTextField5.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter Emp ID field", "Error", JOptionPane.ERROR_MESSAGE);  }
        else if(jTextField9.getText().isEmpty()){myflag=false; JOptionPane.showMessageDialog(this, "Please enter ST ID field", "Error", JOptionPane.ERROR_MESSAGE);  }
        if(myflag){
            try {
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String url="jdbc:oracle:thin:@localhost:1521:orcl";
                Connection con =DriverManager.getConnection(url, "c##samah", "SHH123456");
                Statement stmt=con.createStatement();//sql not beans!!!!!!!

                // String s6=
                String strStmt="insert into animal values("+this.jTextField1.getText()+",'"+this.jTextField2.getText()+"',"+this.jTextField3.getText()+","+this.jTextField4.getText()+","+this.jTextField7.getText()+",'"+this.jTextField8.getText()+"',"+this.jTextField5.getText()+","+this.jTextField9.getText()+")";// //"+this.TBirthDate.getDate()+"
                stmt.executeUpdate(strStmt);//((JTextField)TBirthDate.getDateEditor().getUiComponent()).getText()

              //  JOptionPane.showMessageDialog(this, "We add new row successfully !");
                formWindowOpened(null);
                setVisible(false);
                //setVisible(true);
                new animal_done().setVisible(true);
                  //setVisible(false);
                //DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
                //model.addRow(new Object[]{ jTextField1.getText(), jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText()            });
                
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");

                // con.commit();//save what happened
                con.close();//close the connection

            } catch (Exception ex) {
                //Logger.getLogger(create_account.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,ex.toString());
            }

        }//enf if myflag
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
jButton3.setEnabled(false);
jButton5.setEnabled(false);
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con =DriverManager.getConnection(url, "c##samah", "SHH123456");
            Statement st=con.createStatement();//sql not beans!!!!!!!
          //  String sql="select * from fertilizir";
            ResultSet rs=st.executeQuery("select * from animal");
            /*
             res.last();
            int row=res.getRow();
            int col=res.getMetaData().getColumnCount();
            res.beforeFirst();
            int r=0;
            String rowData[][]=new String[row][col];
            while(res.next()){
                for(int i=0;i<col;i++){
                    if(i==1){
                 rowData[r][i]=res.getString(i+1);}
                    else {
                        rowData[r][i]=String.valueOf(res.getInt(i+1));
                        
                    }
                    
                }
                r++;
                
            }
            
            String [] columnName={"FERT_ID","FERT_NAME","QUANTITY","SALARY","E_ID"};
            DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
            
            model.setDataVector(rowData, columnName);*/
           // jTable2.set
            DefaultTableModel tblModel=(DefaultTableModel)jTable2.getModel();
           //tblModel.setRowCount(0);
            while(rs.next()){
                String id=String.valueOf(rs.getInt(1));
                String name=rs.getString(2);
                String quantity=String.valueOf(rs.getInt(3));
                String salary=String.valueOf(rs.getInt(4));
                String deg=String.valueOf(rs.getInt(5));
                String tox=rs.getString(6);
             
                String empid=String.valueOf(rs.getInt(7));
String fid=String.valueOf(rs.getInt(8));
                String tbData[]={id,name,quantity,salary,deg,tox,empid,fid};
                
                //model.addRow(new Object[]{ id, name,quantity,salary,empid
                    tblModel.addRow(tbData);

                }

               
            
             con.close();
            } catch (Exception ex) {
               // Logger.getLogger(PLANT.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        
       

    }//GEN-LAST:event_formWindowOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
     int id=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
        jButton1.setEnabled(false);
          jButton6.setEnabled(false);
        try {
            // TODO add your handling code here:
             DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con =DriverManager.getConnection(url, "c##samah", "SHH123456");
            Statement st=con.createStatement();//sql not beans!!!!!!!
            ResultSet res=st.executeQuery("select * from animal where animal_id="+id);
            while(res.next()){
                String a=String.valueOf(res.getInt(1));
                
                jTextField1.setText(  a );
                jTextField2.setText(  res.getString(2) );
                jTextField3.setText(  String.valueOf(res.getInt(3)) );
                jTextField4.setText(  String.valueOf(res.getInt(4)) );
                jTextField7.setText(  String.valueOf(res.getInt(5)) );
                 jTextField8.setText(  res.getString(6) );
                 jTextField5.setText(  String.valueOf(res.getInt(7)) );
                 jTextField9.setText(  String.valueOf(res.getInt(8)) );
                
                
            }
            
        } catch (Exception ex) {
            //Logger.getLogger(fert.class.getName()).log(Level.SEVERE, null, ex);
       JOptionPane.showMessageDialog(this, ex.toString(),"ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        jButton3.setEnabled(true);
        jButton5.setEnabled(true);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

 int id=0;
    // jTable2.isR
     if(jTable2.getSelectionModel().isSelectionEmpty() )
         id=Integer.parseInt(jTextField6.getText());
     else {
     
     id=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
     } 
      //  if(jTable2.isRowSelected()) id=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
        
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con =DriverManager.getConnection(url, "c##samah", "SHH123456");
            Statement st=con.createStatement();//sql not beans!!!!!!!
            
            int r=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete selected row? ");
            
            if(r==0){
                if(!st.execute("delete from animal where animal_ID="+id)){
                formWindowOpened(null);
                setVisible(false);
                //setVisible(true);
                new animal_done().setVisible(true);
                
                }
            }
            else{
                //JOptionPane.showMessageDialog(this, "Error ! Try again");
                
            }
            
            
            
        } catch (Exception ex) {
            //Logger.getLogger(fert.class.getName()).log(Level.SEVERE, null, ex);
       JOptionPane.showMessageDialog(this, ex.toString(),"ERROR", JOptionPane.ERROR_MESSAGE);
        
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     //   formWindowOpened(null);
     
               formWindowOpened(null);
                setVisible(false);
                //setVisible(true);
                new animal_done().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     int id=0;
    // jTable2.isR
     if(jTable2.getSelectionModel().isSelectionEmpty() )
         id=Integer.parseInt(jTextField6.getText());
     else {
     
     id=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
     } 
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con =DriverManager.getConnection(url, "c##samah", "SHH123456");
            Statement st=con.createStatement();//sql not beans!!!!!!!
            boolean b=st.execute("update animal set animal_ID="+this.jTextField1.getText()+" ,animal_NAME='"+this.jTextField2.getText()+"'   ,QUANTITY="+this.jTextField3.getText()+"    ,SALARY="+this.jTextField4.getText()+"     , sleephour="+this.jTextField7.getText()+", color='"+this.jTextField8.getText()+"'   ,e_id="+this.jTextField5.getText()+",s_ID="+this.jTextField9.getText()+"   where animal_id="+id);
            if(!b){
                formWindowOpened(null);
                setVisible(false);
                //setVisible(true);
                new animal_done().setVisible(true);
                
            }
        } catch (Exception ex) {
            //Logger.getLogger(fert.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(this, ex.toString(),"ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
       
        
   
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        jButton3.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(false);
        String myString=jTextField6.getText();
        if(myString.isEmpty()){
          JOptionPane.showMessageDialog(this, "Please enter id to search for !", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
         
            
              try {
            // TODO add your handling code here:
           // Date d=dateChooser1.getDate();
           boolean myflag=false;
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            Connection con =DriverManager.getConnection(url, "c##samah", "SHH123456");
            Statement stmt=con.createStatement();//sql not beans!!!!!!!
           String s1="",s2="",s3="",s4="",s5="",s6="",s7="",s8="";
           // String s6=
            String strStmt="select * from animal";
            ResultSet rs=stmt.executeQuery(strStmt);//
            while(rs.next()){
                int theid=rs.getInt(1);
               // String thepas=rs.getString(2);
                if (  (theid==Integer.parseInt(jTextField6.getText()))              ){myflag=true;
                s1=String.valueOf(rs.getInt(1));
                s2=rs.getString(2);
                s3=String.valueOf(rs.getInt(3));
                s4=String.valueOf(rs.getInt(4));
                s5=String.valueOf(rs.getInt(5));
                s6=rs.getString(6);
                
                
                s7=String.valueOf(rs.getInt(7));
                s8=String.valueOf(rs.getInt(8));
                
                }
            }
            if(myflag){
               jTextField1.setText(s1);
               jTextField2.setText(s2);
               jTextField3.setText(s3);
               jTextField4.setText(s4);
               jTextField7.setText(s5);
               jTextField8.setText(s6);
               jTextField5.setText(s7);
               jTextField9.setText(s8);
               
               
            //new home().setVisible(true);
            //setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(this, "You have entered unexist values !", "Error", JOptionPane.ERROR_MESSAGE);
            }
            //con.commit();//save what happened
            con.close();//close the connection
            
        } catch (Exception ex) {
            //Logger.getLogger(create_account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.toString());
        }
         
        }//end else
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animal().setVisible(true);
                //JOptionPane.showMessageDialog(null,"hi");
                
                 
        
        
            
      
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
